### ISSUE TITLE
`graphchecker` reports errors on graphs with weights

### ISSUE THREAD

**Issue by bahorn** [KarlsruheMIS/KaMIS#13]
So I noticed that `graphchecker` will report errors on graphs defined with weights. Seems `ew` is only read in but not used, so some extra logic is needed to handle both edge and node weights.

## Reproduction

To give a test case, I modified `examples/simple.graph` to have node weights:

```
6 7 10
1 2 6
2 1 3 6
1 2 4
2 3 5
1 4 6
2 1 2 5
```

Which can be solved with `weighted_branch_reduce`, but `graphchecker` reports:
```
The number of edges specified in the beginning of the file does not match the number of edges that are in the file.
You specified 14 but there are 20
```

## Potential Fix

I wrote a patch by taking the extra checks from KaHIPs and made it conform to the styling: https://github.com/bahorn/KaMIS/commit/b3ddbcd722903f9b308f45514a0e38f4496c45a6

Though seems it's possible just to rip it from the repo directly.

**Comment by schulzchristian** [comment]
Thanks for your input! Actually, edge weights should just be ignored at all --- they don't make sense for the IS problem.
Could you adapt your code accordingly and issue a pull request?

Best
Christian
