### ISSUE TITLE
Outputting Vertices from found Exact  Independent Weighted Set 

### ISSUE THREAD

**Issue by charlieh108** [KarlsruheMIS/KaMIS#16]
Hi all,

I’m using KaMIS to find the exact Maximum Weighted Independent sets for some small weighted Erdős–Rényi graphs (Number of Vertices< 20)  and am using the functions `weighted_branch_reduce` & `weighted_local_search` to do so. 

Is there a method to output the vertices that form the found set ? From what I can tell, the ` --output` method only gives the maximum weight found. This is in contrast to the same method in `ReduMIS`, which gives the vertices in a maximum unweighted independent set. Is there a special usage  needed to get the maximum weight set out? Or is there a simple code change I can implement to do this ? 

Second of all, as these are small graphs compared to the problems solved [in this](https://doi.org/10.1137/1.9781611975499.12) paper, will these methods always give the exact solution?  
I’m using a Mac OS 10.15.7 with a C++ installation from Xcode, and followed the instructions in the Github to install the package.

**Comment by schulzchristian** [comment]
Dear Charlie,
I added the functionality to the program. Let me know if you have any other questions or if there is anything else that we can help you with.

Best
Christian

**Comment by charlieh108** [comment]
Dear Prof Schulz, 

It works perfectly - thank you so much !

I hope you have a lovely weekend !

Many thanks, 

Charlie

**Comment by CheRaissi** [comment]
Hello @schulzchristian, 

I think the committed code is not working with the local search program weighted_local_search.

Here is an example of the execution on the sample weighted graph with the branch and reduce:

```
$ ./weighted_branch_reduce ../examples/weight_nodes.graph --output=test.txt

reduction_time 4.88758e-05
time 0.00012
MIS_weight 4
MIS_weight_check 4
writing independent set to test.txt ...
$ cat test.txt
0
1
0
1
0
0
```

and with the local search: 

```
$ ./weighted_local_search ../examples/weight_nodes.graph --output=test.txt
$ cat test.txt
%reduction_time 6.9e-05
%reduction_offset 4
0 0 10
```

I believe that the problem is located in [https://github.com/KarlsruheMIS/KaMIS/blob/60756c80cabe16079c924bf44be5196fc9308637/wmis/app/weighted_ls.cpp#L177](url):

```
if (mis_config.write_graph) {
                // just reduce the graph and write it into a file
                graph_access rG;

                auto start = std::chrono::system_clock::now();
                weight_offset = perform_reduction(reducer, G, rG, mis_config);
                auto end = std::chrono::system_clock::now();

                std::chrono::duration<float> reduction_time = end - start;

                std::ofstream output_reduced(mis_config.output_filename);

                output_reduced << "%reduction_time " << reduction_time.count() << "\n";
                output_reduced << "%reduction_offset " << weight_offset << "\n";

                graph_io::writeGraphNodeWeighted(rG, output_reduced);
                return 0;
        }
```

Thanks!

**Comment by schulzchristian** [comment]
Hi, I will fix this tomorrow, sorry for the delay.

Best
Christian

**Comment by schulzchristian** [comment]
It should work now.
Thanks for reporting this.

Best
Christian
