### ISSUE TITLE
Predicting memory usage

### ISSUE THREAD

**Issue by Darksonn** [KarlsruheMIS/KaMIS#24]
Is there any way to predict how much memory KaMIS will use to process a certain input? For example, if I start KaMIS and run it for five minutes, would the maximum memory that it uses within those five minutes be a reasonable upper bound for how much memory it will use later, or do I risk that it enters some new phase later that requires a lot more memory than what it needed during the first five minutes?

I'm going to use this information to properly allocate resources to jobs that I am starting on a HPC cluster.

**Comment by schulzchristian** [comment]
Hi, here is what I would do: can you measure the memory consumption on smaller instances and check the dependency? My guess would be c(n+m). Then you can probably interpolate for larger instances. You can do the measurements using valgrind —tool=massif …

@sebalamm do you have a better idea?

Hope this helps a little bit.
Christian
