### ISSUE TITLE
OnlineMIS not terminating

### ISSUE THREAD

**Issue by schulzchristian** [KarlsruheMIS/KaMIS#25]
On the following graph

graph.metis:
2 1
2
1

./deploy/online_mis ~/Desktop/test_graph_1edge.txt --time_limit=2
is not terminating.

**Comment by schulzchristian** [comment]
also on this one:

7 8
2 3 4 5 6
1 3 6
1 2
1 5
1 4
1 2

**Comment by sebalamm** [comment]
I'll take a look at it

**Comment by sebalamm** [comment]
Should be fixed now. There was an error when graphs are solved directly and the local search tried to find vertices for forceful insertion.
