### ISSUE TITLE
Negative weights

### ISSUE THREAD

**Issue by Paulkie99** [KarlsruheMIS/KaMIS#35]
Hi, is there a way to adapt this program to work when finding the MWIS from graphs that contain negative weights? 

Thanks.

**Comment by schulzchristian** [comment]
Do you still want to maximize? Because in this case none of the vertices with negative weight would be in an maximum weight independent set (you can simply remove thel in a preprocessing step). Or what is the problem variation you are considering?

Best
Christian

**Comment by Paulkie99** [comment]
Hi Christian, I have done some more investigation after removing negative nodes.

I think the unexpected behaviour (read: solutions) I am encountering are actually due to the rounding off of floating point weights in my original graphs. So perhaps a more appropriate question would be whether KaMIS can be adapted for floating point weights?

**Comment by schulzchristian** [comment]
I don't believe this is currently possible (correct me if I am wrong @ernestine-grossmann @darrenstrash); the only solution I see is scaling the weights before rounding to get a more accurate solution. However, the sum of the weights likely has to fit into an int (again correct me if I am wrong Ernestine, Darren). 

Best
Christian

**Comment by darrenstrash** [comment]
As far as I am aware, we are not able to handle floating point weights.
However, I would be happy to consider a pull request that implements this
feature!
