### ISSUE TITLE
OnlineMIS doesn't seem to terminate on complete graphs

### ISSUE THREAD

**Issue by default-username-852** [KarlsruheMIS/KaMIS#37]
Currently OnlineMIS doesn't terminate when given complete graphs with 4 or more vertices. For example, the inputs

K4:
```
4 6
2 3 4
1 3 4
1 2 4
1 2 3
```

K5:
```
5 10
2 3 4 5
1 3 4 5
1 2 4 5
1 2 3 5
1 2 3 4
```

make the program get stuck in an infinite loop.

**Comment by schulzchristian** [comment]
Hi, it is not in an infinite loop. The program has a time_limit which is set to 1000 by default.  If you set the time_limit smaller, i.e. --time_limit=0, then it directly converges.
