### ISSUE TITLE
ReduMIS and OnlineMIS does not work for regular graphs

### ISSUE THREAD

**Issue by yikai-wu** [KarlsruheMIS/KaMIS#42]
I tried both ReduMIS and OnlineMIS for unweighted random d-regular graphs (every node has degree d). Both do not find an independent set and report either inconsistency or block weight limit reached. While using greedy algorithms I can easily find some independent sets for these graphs.

My random d-regular graphs are generated using the default function in Networkx (Python) and transformed into input files for ReduMIS and OnlineMIS. The same procedure works well for Erdos-Renyi graphs and other types of graphs.

It seems from the papers of ReduMIS and OnlineMIS, they should report a MIS at least as good as one found by greedy algorithms, so it seems that the implementation may have some problems.

May I know if you could try to reproduce the issue and find the cause of the problem? It would be better if you can fix it and update the codes.

Thank you very much.

**Comment by schulzchristian** [comment]
Hi, can you try to run the graph checker on your input instances? If this graphchecker tools says the instances are ok, then please share them with us.

**Comment by yikai-wu** [comment]
I ran the graph checker and found that it was caused by having self loops. It works well with fixed graphs. Thank you very much.
